name: (disabled) Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Skip legacy workflow
        run: echo "This legacy workflow is disabled. Use deploy.yml."
        shell: bash
        if: ${{ false }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and export static site
        env:
          GITHUB_ACTIONS: 'true'
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: pnpm export

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Skip deploy
        run: echo "Disabled"
        shell: bash
        if: ${{ false }}


